# Generated by Django 5.1.5 on 2025-02-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sentimentanalysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentimentAnalysis',
        ),
    ]
